apiVersion: v2
name: switcher-api
home: https://github.com/switcherapi/helm-charts
description: A Switcher API Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/switcherapi/switcherapi-assets/master/logo/switcher_mark_grey.png

type: application
version: 1.0.2
appVersion: "1.2.6"